added vertical format for text
bjesus/wttrbar pull request #18
Opened 2023-10-21 15:18 UTC by BluewyDiamond

There might be people who uses waybar in a vertical setup, thus having a vertical format would be very appreciated.

2023-10-21 15:33 UTC, bjesus requested changes

2023-10-21 15:33 UTC, bjesus commented on main.rs
> +
can we read this argument like we're reading the others? e.g.
```
    let ampm = args.iter().any(|arg| arg == "--ampm");
```

2023-10-21 15:33 UTC, bjesus commented on main.rs
> +    let text = if vertical_view == true {
do we need this `== true` ?

2023-10-21 17:59 UTC, BluewyDiamond commented
I have changed it according to the requests. Is it good?

2023-10-23 16:40 UTC, merged

2023-10-23 16:40 UTC, bjesus commented
lgtm! thank you

2024-05-20 07:36 UTC, bjesus commented
this feature will be deprecated and removed soon. please use    `wttrbar --custom-indicator '{ICON}\n{temp_C}'` instead.